-- dcm/definitions/tables.sql
-- Declarative table definitions for the git-sis schema.
--
-- Managed by DCM (snow dcm). Do NOT edit via Snowsight or raw ALTER TABLE —
-- changes must go through the DCM plan/deploy workflow to maintain state.
--
-- To preview changes: make dcm-plan
-- To apply changes:   make dcm-deploy
--
-- Reference: deploy/00_setup_env.sql is retained as a non-DCM fallback
-- (for fresh environments without a DCM project object in place).

-- Orders table: each row is a synthetic order generated by run_ingestion().
DEFINE TABLE ORDERS (
    ORDER_ID    STRING        NOT NULL  COMMENT 'UUID generated by UUID_STRING()',
    RUN_ID      STRING        NOT NULL  COMMENT 'Foreign key to INGEST_LOG.RUN_ID',
    CUSTOMER_ID NUMBER        NOT NULL  COMMENT 'Synthetic customer identifier (1-1000)',
    AMOUNT      FLOAT         NOT NULL  COMMENT 'Order value in USD',
    REGION      STRING        NOT NULL  COMMENT 'Geographic region: NA, EMEA, APAC, LATAM',
    ORDER_TS    TIMESTAMP_LTZ NOT NULL  COMMENT 'Order creation timestamp'
);

-- Ingest log table: structured logging for every ingestion run.
-- STATUS transitions: RUNNING → SUCCESS | FAILED
DEFINE TABLE INGEST_LOG (
    RUN_ID      STRING        NOT NULL  COMMENT 'UUID; also used as a correlation key in ORDERS',
    PROC_NAME   STRING        NOT NULL  COMMENT 'Name of the ingestion procedure (ingest_orders)',
    STATUS      STRING        NOT NULL  COMMENT 'RUNNING | SUCCESS | FAILED',
    ROWS_LOADED NUMBER                  COMMENT 'Rows written to ORDERS; NULL while RUNNING',
    ERROR_CODE  STRING                  COMMENT 'Short error code; NULL on success',
    ERROR_MSG   STRING                  COMMENT 'Full error message; NULL on success',
    STARTED_AT  TIMESTAMP_LTZ          COMMENT 'Run start time',
    ENDED_AT    TIMESTAMP_LTZ          COMMENT 'Run end time; NULL while RUNNING'
);
